# Name of website
title: AS.430.618 
description: Advanced Python Scripting for GIS
show_downloads: true


theme: jekyll-theme-dinky

highlighter: yellow
markdown: kramdown
# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "achapko1@jhu.edu"
  github: achapkowski
  twitter: achapkowski
